version: "3.9"

services:
  web_server:
    image: nginx:1.23.3-alpine
    volumes:
      - ./default.nginx:/etc/nginx/nginx.conf
      - ./html/:/www/html/
      - ./images/:/www/images/
    ports:
      - 3000:80
      - 3001:81
      - 3002:82
