version: "3.9"

services:
  web_server:
    image: nginx:1.23.3-alpine
    volumes:
      - ./conf.nginx:/etc/nginx/conf.d/default.conf
      - ./html/:/www/html/
      - ./images/:/www/images/
    ports:
      - 3000:80
