version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80

  node_one:
    image: node:18.14.1-bullseye-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run start
    environment:
      MESSAGE: node one
