version: '3.9'

services:
  nginx_one:
    image: nginx:1.23.3-alpine
    volumes:
      - ./one.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - 3000:80
  nginx_two:
    image: nginx:1.23.3-alpine
    volumes:
      - ./two.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - 3001:80

  node_one:
    image: node:18.14.1-bullseye-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run start
  node_two:
    image: node:18.14.1-bullseye-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run start
  node_three:
    image: node:18.14.1-bullseye-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run start
  node_four:
    image: node:18.14.1-bullseye-slim
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    command: npm run start
